version: '3'

services:
  mysql-loja:
    image: mysql:latest
    container_name: mysql-loja
    environment:
      MYSQL_ROOT_PASSWORD: senhasegura
      MYSQL_DATABASE: loja
    ports:
      - "3307:3306"
    volumes:
      - mysql-volume-loja:/var/lib/mysql
    networks:
      - network-loja

  phpmyadmin-loja:
    image: phpmyadmin/phpmyadmin
    container_name: phpmyadmin-loja
    depends_on:
      - mysql-loja
    environment:
      PMA_HOST: mysql-loja
      PMA_PORT: 3306
      PMA_USER: root
      PMA_PASSWORD: senhasegura
    ports:
      - "8080:80"
    networks:
      - network-loja

volumes:
  mysql-volume-loja:

networks:
  network-loja:
